# Generated by Django 3.0.8 on 2020-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hey there, I am on Blogbuzz. Stay tuned to view my blogs.'),
            preserve_default=False,
        ),
    ]
